#ifndef OPENCV_FORMAT_CONVERT_GLOBAL_H
#define OPENCV_FORMAT_CONVERT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OPENCV_FORMAT_CONVERT_LIBRARY)
#  define OPENCV_FORMAT_CONVERT_EXPORT Q_DECL_EXPORT
#else
#  define OPENCV_FORMAT_CONVERT_EXPORT Q_DECL_IMPORT
#endif

#endif // OPENCV_FORMAT_CONVERT_GLOBAL_H
