#ifndef SERIAL_WRAPPER_GLOBAL_H
#define SERIAL_WRAPPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERIAL_WRAPPER_LIBRARY)
#  define SERIAL_WRAPPER_EXPORT Q_DECL_EXPORT
#else
#  define SERIAL_WRAPPER_EXPORT Q_DECL_IMPORT
#endif

#endif // SERIAL_WRAPPER_GLOBAL_H
