#ifndef TEXT_WRITE_SEEKER_GLOBAL_H
#define TEXT_WRITE_SEEKER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEXT_WRITE_SEEKER_LIBRARY)
#  define TEXT_WRITE_SEEKER_EXPORT Q_DECL_EXPORT
#else
#  define TEXT_WRITE_SEEKER_EXPORT Q_DECL_IMPORT
#endif

#endif // TEXT_WRITE_SEEKER_GLOBAL_H
